#################### Server Configuration ####################
server:
  port: 8084
  servlet.context-path: /balance-service-1.0
  tomcat:
    accept-count: 100
    threads:
      min-spare: 10
      max: 200

#################### Management Configuration ####################
management:
  server:
    port: 8085
  info:
    git.enabled: true
    build.enabled: true
  endpoints.web.exposure.include: '*'

#################### External Route Configuration ####################
http.route.map:
  THS:
    scheme: http
    host: localhost
    port: 8086
    contextPath: /transaction-history-service-1.0
    maxConnection: 200
